### ISSUE TITLE
[Add Mega.nz api Support] 

### ISSUE THREAD

**Issue by Cyberillc** [MaxMaeder/DriveBackupV2#165] opened 2024-05-21 21:27 UTC
### What feature do you want to see added?

I want to add mega.nz api support since it allows more storage than google drive or onedrive for free. i am asking for this because my world size is big (4.6 GB)
ApI:https://mega.io/developerss

### Are there any alternatives?

Onedrive (4 GB),Google Drive(15 GB),Mediafire(10 GB)

**Comment by jschenke488** [comment] 2024-06-05 04:39
https://github.com/MaxMaeder/DriveBackupV2/issues/142#issuecomment-1888838442

**Comment by lrmtheboss** [comment] 2024-06-13 17:10
Duplicate off #142 
the link you included does not contain API documentation just documentation for their already existing apps and SDKs.
They currently don't have a REST API or a java SDK so we're unable to add support at this time.

**Closed by lrmtheboss** 2024-06-13 17:10 UTC
