### ISSUE TITLE
google drive link

### ISSUE THREAD

**Issue by FakEEE14** [MaxMaeder/DriveBackupV2#77] opened 2021-12-12 09:08 UTC
### Describe the bug

on 1.5.0 and after have a link problem
but i use older version (1.4.0) it's fine

### To Reproduce

just drop the drivebackupv2 version 1.5.0 beta1 and above in plugins folder
with a fresh config change the googledrive from false to true
just /drivebackup linkaccount googledrive
and this

### Additional Context

https://pastebin.com/efaFiwLn

**Comment by rhld16** [comment] 2021-12-12 10:00
The latest version of DriveBackupV2 is 1.5.4 which you can download from https://dev.bukkit.org/projects/drivebackupv2

**Comment by FakEEE14** [comment] 2021-12-12 10:11
i know
i try /drivebackup linkaccount googledrive and it's pop the pastebin error

**Comment by rhld16** [comment] 2021-12-12 10:27
Could you paste the result of `/drivebackup v` here?

**Comment by FakEEE14** [comment] 2021-12-23 07:30
![image](https://user-images.githubusercontent.com/68513641/147204657-bc1c0e6f-8365-4783-9f9e-8a25a33df774.png)

**Comment by VXsz** [comment] 2021-12-23 13:17
Same issue:
```
[13:11:43 WARN]: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
[13:11:43 WARN]: {
[13:11:43 WARN]:   "code" : 404,
[13:11:43 WARN]:   "errors" : [ {
[13:11:43 WARN]:     "domain" : "global",
[13:11:43 WARN]:     "location" : "file",
[13:11:43 WARN]:     "locationType" : "other",
[13:11:43 WARN]:     "message" : "File not found: ",
[13:11:43 WARN]:     "reason" : "notFound"
[13:11:43 WARN]:   } ],
[13:11:43 WARN]:   "message" : "File not found: "
[13:11:43 WARN]: }
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
[13:11:43 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
[13:11:43 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.googledrive.GoogleDriveUploader.<init>(GoogleDriveUploader.java:84)
[13:11:43 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.Authenticator$1.run(Authenticator.java:164)
[13:11:43 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:11:43 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1571)
[13:11:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:516)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1494)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1282)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[13:11:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:11:43 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.drives" is null
[13:11:43 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.googledrive.GoogleDriveUploader.setupSharedDrives(GoogleDriveUploader.java:287)
[13:11:43 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.Authenticator$1.run(Authenticator.java:164)
[13:11:43 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:11:43 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1571)
[13:11:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:516)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1494)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1282)
[13:11:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[13:11:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rhld16** [comment] 2022-01-16 10:56
This issue has since been fixed could you test the latest build from Actions tab?

**Comment by VXsz** [comment] 2022-01-18 21:39
it's been a _long_ time, I can't test it anymore sadly... but there's a good chance I was a retarded that didn't put a token (or something like that) in the config files

**Comment by rhld16** [comment] 2022-01-19 21:26
Ah don't worry, since this issue is confirmed to be resolved by another user I'll close it.

**Closed by rhld16** 2022-01-19 21:26 UTC
