### ISSUE TITLE
failed to invoke google api

### ISSUE THREAD

**Issue by 0withoutface0** [MaxMaeder/DriveBackupV2#95] opened 2022-05-10 17:14 UTC
### Describe the bug

hello! today the bukkit plugin just stopped working
thanks for help
here is the log

```
>drivebackup backup
[19:06:09] [Server thread/INFO]: [DriveBackupV2] Forcing a backup
[19:06:09] [Thread-11382/WARN]: java.lang.NullPointerException: Cannot invoke "com.google.api.services.drive.Drive.drives()" because "this.service" is null
[19:06:09] [Thread-11382/WARN]:         at ratismal.drivebackup.uploaders.googledrive.GoogleDriveUploader.<init>(GoogleDriveUploader.java:84)
[19:06:09] [Thread-11382/WARN]:         at ratismal.drivebackup.UploadThread.run(UploadThread.java:199)
[19:06:09] [Thread-11382/WARN]:         at java.base/java.lang.Thread.run(Thread.java:833)
[19:06:09] [Thread-11382/INFO]: [DriveBackupV2] Skipping backup to Google Drive, account not yet linked
[19:06:09] [Thread-11382/INFO]: To link your account, run /drivebackup linkaccount googledrive
[19:06:09] [Thread-11382/INFO]: [DriveBackupV2] Creating backups, the server may lag for a little while...
[19:06:10] [Thread-11382/INFO]: [DriveBackupV2] Doing backups for ".\world"
[19:08:28] [Thread-11382/INFO]: [DriveBackupV2] There are 4 file(s) which exceeds the local limit of 3, deleting oldest
[19:08:28] [Thread-11382/INFO]: [DriveBackupV2] Doing backups for ".\world_nether"
[19:08:42] [Thread-11382/INFO]: [DriveBackupV2] There are 4 file(s) which exceeds the local limit of 3, deleting oldest
[19:08:42] [Thread-11382/INFO]: [DriveBackupV2] Doing backups for ".\world_the_end"
[19:08:50] [Thread-11382/INFO]: [DriveBackupV2] There are 4 file(s) which exceeds the local limit of 3, deleting oldest
[19:08:50] [Thread-11382/INFO]: [DriveBackupV2] Doing backups for "plugins"
[19:08:53] [Thread-11382/INFO]: [DriveBackupV2] There are 4 file(s) which exceeds the local limit of 3, deleting oldest
[19:08:53] [Thread-11382/INFO]: [DriveBackupV2] Backup complete
```

### To Reproduce

start the plugin :D

### Server and Plugin Versions

```
DriveBackupV2 v1.6.0
CraftBukkit version 3467-Bukkit-e6cc7c7 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
```

**Comment by 0withoutface0** [comment] 2022-05-10 17:22
Ok so i did a little fixing and i figured out that the plugin deleted his own folder. I reinstalled it and now its working, but this is still a bug so i will not close this issue.

**Comment by rhld16** [comment] 2022-05-22 07:42
The plugin is not able to delete it’s own folder, so I’ll close the issue for now. If it reoccurs, please open a new issue in order to identify the root cause

**Closed by rhld16** 2022-05-22 07:42 UTC
