### ISSUE TITLE
Cannot invoke "java.util.Map$Entry.getValue()" because the return value of "java.util.NavigableMap.firstEntry()" is null

### ISSUE THREAD

**Issue by nishio** [MaxMaeder/DriveBackupV2#71] opened 2021-10-05 20:26 UTC
### Describe the bug

The backup to Dropbox sometimes throw exception as follows:

```
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getValue()" because the return value of "java.util.NavigableMap.firstEntry()" is null
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:357)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:231)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:02:39] [Craft Scheduler Thread - 2641 - DriveBackupV2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

It is not always. Sometimes backup succeeds. It fails about 50% probability.

### To Reproduce

Install this plugin into Paper and configure Dropbox connection.

### Server and Plugin Versions

```
[09:00:20] [Server thread/INFO]: This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)
[09:00:31] [Server thread/INFO]: [DriveBackupV2] Loading DriveBackupV2 v1.5.2
```

### Additional Context

I'm not sure it is related the issue, there is also SocketException.

```
[10:01:10] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Doing backups for "./world_the_end"
[10:01:12] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Uploading file to Dropbox
[10:01:16] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] There are 21 file(s) for the current backup location in Dropbox which exceeds the limit of 20, deleting
[10:01:17] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] File uploaded in 4.1 seconds (5677.48KB/s)
[10:01:17] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] There are 25 file(s) which exceeds the local limit of 24, deleting oldest
[10:01:17] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Doing backups for "./world_nether"
[10:01:20] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Uploading file to Dropbox
[10:01:25] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] There are 21 file(s) for the current backup location in Dropbox which exceeds the limit of 20, deleting
[10:01:26] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] File uploaded in 6.29 seconds (7022.43KB/s)
[10:01:26] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] There are 25 file(s) which exceeds the local limit of 24, deleting oldest
[10:01:26] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Doing backups for "./world"
[10:02:19] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Uploading file to Dropbox
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [java.net.SocketException: Connection reset by peer, java.net.SocketException: Connection reset by peer]
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: java.net.SocketException: Network is unreachable
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:576)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:565)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.net.Socket.connect(Socket.java:645)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.platform.Platform.connectSocket(Platform.kt:120)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.RealConnection.connect(RealConnection.kt:195)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.RealCall.execute(RealCall.kt:148)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.uploadFile(DropboxUploader.java:226)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:367)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:231)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	Suppressed: java.net.SocketException: Connection reset by peer
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:342)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1287)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.OutputStreamSink.write(JvmOkio.kt:53)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.write(RealBufferedSink.kt:145)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.ForwardingSink.write(ForwardingSink.kt:29)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.write(RealBufferedSink.kt:176)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RequestBody$Companion$toRequestBody$2.writeTo(RequestBody.kt:152)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		... 18 more
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	Suppressed: java.net.SocketException: Connection reset by peer
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:342)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1287)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.OutputStreamSink.write(JvmOkio.kt:53)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.write(RealBufferedSink.kt:145)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.kt:271)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.ForwardingSink.write(ForwardingSink.kt:29)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RealBufferedSink.write(RealBufferedSink.kt:176)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.RequestBody$Companion$toRequestBody$2.writeTo(RequestBody.kt:152)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 		... 18 more
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Failed to upload
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] There are 25 file(s) which exceeds the local limit of 24, deleting oldest
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Doing backups for "plugins"
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Failed to upload
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map$Entry.getValue()" because the return value of "java.util.NavigableMap.firstEntry()" is null
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:357)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:231)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Failed to backup to Dropbox, verify all credentials are correct or diagnose the problem with /drivebackup test dropbox
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] Backup complete
[10:02:36] [Craft Scheduler Thread - 251 - DriveBackupV2/INFO]: [DriveBackupV2] The next backup is in 58 minutes
```

**Comment by rhld16** [comment] 2022-02-05 16:41
Closing due to unreproducibility

**Closed by rhld16** 2022-02-05 16:41 UTC
